### PR TITLE
Add percent chance of jumpscare

### PR DESCRIPTION
**Pull request by undefined06855**
among other small things

### CODE REVIEW

**Comment by undefined06855** [comment]
wait hold on it didnt add mod.json to the commit

**Comment by undefined06855** [comment]
wait i didnt mean to close it :sob:

**Comment by undefined06855** [comment]
ok yeah it's good now tell me what you think

**Comment by undefined06855** [comment]
just wondering if you still work on this

**Comment by NicknameGG** [comment]
oh my god i'm so sorry i didn't see the PR i will check it in a bit

**Comment by NicknameGG** [comment]
I think it good :+1:

**Pull request merged**
